apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: kustomize-
nameSuffix: -prod
resources:
- https://raw.githubusercontent.com/tyriis/kustomize-playground/main/base/kustomization.yaml
# - namespace.yaml
# patches:
# - guestbook-ui-svc.yaml
patchesStrategicMerge:
- guestbook-ui-svc.yaml
namespace: default