apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
# - namespace.yaml
patches:
- guestbook-ui-svc.yaml
# patchesStrategicMerge:
# - guestbook-ui-svc.yaml
namespace: default