apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
# - namespace.yaml
# patchesJson6902:
# - path: ingress-patch.yaml
#   target:
#     group: networking.k8s.io
#     kind: Ingress
#     name: devops-toolkit
patchesStrategicMerge:
- guestbook-ui-svc.yaml
namespace: default